config/routes.rb
ExposeIdeas::Application.routes.draw do

  resources :comments

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root to: 'ideas#index'
  
  match 'sessions/delete' => 'sessions#destroy'
  match 'ideas/:id/scoreup' => 'ideas#scoreup', :as => :scoreup_idea
  match 'ideas/:id/changestatus' => 'ideas#changestatus', :as => :changestatus_idea
  
  resources :users

  resources :ideas

  resources :sessions

   match ':controller(/:action(/:id))(.:format)'
end

app/models/idea.rb
class Idea < ActiveRecord::Base
  
  belongs_to :user
  belongs_to :category
  has_many :comment

  attr_accessible :title, :body, :category_id, :user_id, :comment_id, :status

  validates :title, :length => { :maximum => 140 }
  validates :body, :length => { :maximum => 2000 }
  validates :user_id, :presence => { :on => :create }
  validates :category_id, :presence => { :on => :create }
  
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_filter :require_login, :except => [:index, :show, :scoreup]
  before_filter :require_admin, :only => [:changestatus]
  before_filter :init

  def init
    if session[:idea_voted].nil? 
      session[:idea_voted] = []
    end
  end

  # GET /ideas
  def index
    if params[:search].present?
      @search = Idea.search(params[:search])
      @ideas = @search.paginate(:page => params[:page], :per_page => 3)   # or @search.relation to lazy load in view // @search.paginate(:page => params[:page])
    else
      if params[:category_id].nil?
        @ideas = Idea.paginate(:page => params[:page], :per_page => 3)
      else
        @ideas = Idea.where(["category_id = ?", params[:category_id]]).paginate(:page => params[:page], :per_page => 3)
      end
    end
    @categories = Category.all
  end

  # GET /ideas/1 
  def show
    @idea = Idea.find(params[:id])
    @comment = Comment.new
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
    @categories = Category.all

  end

  # GET /ideas/1/edit
  def edit    
    @idea = Idea.find(params[:id])
    if @idea.user_id != session[:current_user_authenticated]
      flash[:error] = t(:different_owner)
      redirect_to :back 
    end
    @categories = Category.all
  end

  # POST /ideas
  def create
    @idea = Idea.new(params[:idea])
    @idea.user_id = session[:current_user_authenticated]
    @idea.score = 0
    @idea.published = 0

    if @idea.save
      redirect_to ideas_url, notice: 'Idea was successfully created.' 
    else
      render action: "new" 
    end
  end

  # PUT /ideas/1
  def update
    @idea = Idea.find(params[:id])
    if @idea.update_attributes(params[:idea])
      redirect_to ideas_url, notice: "Idea was successfully updated."
    else
      render action: "edit" 
    end
  end

  # DELETE /ideas/1
  def destroy
    @idea = Idea.find(params[:id])
    if @idea.user_id == session[:current_user_authenticated]
      @idea.destroy
      redirect_to ideas_url, notice: 'Idea was successfully destroyed.' 
    else
      flash[:error] = t(:different_owner)
      redirect_to :back
    end
  end

  # PUT /ideas/1/scoreup
  def scoreup
    if session[:idea_voted].index(params[:id]).nil? 
      @idea = Idea.find(params[:id])
      @idea.score.nil? ? @idea.score = 1 : @idea.score = @idea.score + 1
      @idea.save
      (session[:idea_voted] ||= []) << params[:id]
      redirect_to :back, notice: 'You liked this idea !' 
    else
      flash[:error] = "Already voted"
      redirect_to :back
    end
  end

  # PUT /ideas/1/scoreup
  def changestatus
    # 0. not published / 1. published
    @idea = Idea.find(params[:id])
    @idea.status.nil? || @idea.status == 0 ? @idea.status = 1 : @idea.status = 0
    @idea.save
    redirect_to :back, notice: 'You changed the status of the idea.' 
  end
end

app/helpers/ideas_helper.rb
module IdeasHelper

end

app/views/ideas/_form.html.erb
<%= form_for(@idea) do |f| %>

  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <label id="idea_title"> <%= f.text_field :title, :class => 'span10', :placeholder => 'Your title here...' %> </label> 
  <label id="idea_body"><%= f.text_area :body, :class => 'span10 tinymce', :placeholder => 'Your idea description here...' %> </label> 

  <%= select :idea, "category_id", @categories.map {|c| [c.name,c.id]} %>
  <br />
  <%= f.submit :class => "btn btn-primary btn-normal" %>

<% end %> 

app/views/ideas/edit.html.erb
<legend><%= t :edit_idea %> "<%= @idea.title %>"</legend>

<%= render 'form' %>

app/views/ideas/index.html.erb
<script type="text/javascript">
$(function() {
  $('.ideaBody').truncate();
});
</script>

<div class="container-fluid">

  <div class="hero-unit visible-desktop">
    <h1 id="responsive_headline">Vote for ideas or submit yours !</h1>
    <p>Careerbuilder team is waiting for your feedback to improve existing tools they are creating.</p>
    <br />
    <p style="text-align:center">
      <a href="/ideas/new" class="btn btn-primary btn-large"><%= t(:post_new_idea)%></a>
    </p>
  </div>

  <div class="well well-large visible-tablet">
    <h3 id="responsive_headline">Vote for ideas or submit yours !</h1>
    <p>Careerbuilder team is waiting for your feedback to improve existing tools they are creating.</p>
    <br />
    <p style="text-align:center">
      <a href="/ideas/new" class="btn btn-primary btn-large"><%= t(:post_new_idea)%></a>
    </p>
  </div>

  <div class="well well-small visible-phone">
    <h5 id="responsive_headline">Vote for ideas or submit yours !</h1>
    <p>Careerbuilder team is waiting for your feedback to improve existing tools they are creating.</p>
    <br />
    <p style="text-align:center">
      <a href="/ideas/new" class="btn btn-primary btn-large"><%= t(:post_new_idea)%></a>
    </p>
  </div>

  <div class="tabbable tabs-above hidden-phone">
    <div class="tab-content">Filters ideas: </div>

    
    <ul class="nav nav-tabs">

      <% if params[:category_id].nil? %>
        <li class="active">
      <% else %>
        <li>
      <% end %>
        <%= link_to "All", ideas_url %>
      </li>
      <% @categories.each do |cat| %>
        <% if params[:category_id].to_s == cat.id.to_s %>
          <li class="active">
        <% else %>
          <li>
        <% end %>

          <%= link_to cat.name, ideas_url + "?category_id=#{cat.id}" %>
        </li>
      <% end %>
    </ul>

  </div>

  <% @ideas.each do |idea| %>
      <div class="table table-hover">
      <div class="row-fluid ">

        <div class="span12">
          <%= link_to idea.category.name, ideas_url + "?category_id=#{idea.category_id}", :class =>"btn btn-success btn-mini" %>

          <h4 style="display:inline;"><%= link_to idea.title, idea %></h4>
          <% if idea.status == 0 || idea.status.nil? %> 
            <span style="color:red"><strong>OFFLINE</strong></span>
          <% end %>
        </div>  

      </div>
      
      <div class="row-fluid">
        <div class="span12"> 
          <blockquote>
            <div class="ideaBody"><%= simple_format(idea.body) %></div>
            <small>(<cite>from @<%= idea.user.nickname if idea.user  %>, </cite>
            <%= distance_of_time_in_words_to_now idea.updated_at %>)</small>
        </div>

      </div>
      <div class="row-fluid">
        
        <div class="span9">
          <%= link_to "#comments : #{idea.comment.count}", idea, :anchor => 'commentList' %> 
          | Idea score : <%= idea.score %> 
          <% if session[:idea_voted].index(idea.id.to_s).nil? %>
            | <%= link_to 'I like this idea', scoreup_idea_path(idea) %>
          <% end %>
        </div>

        <% if session[:current_user_authenticated].to_s == idea.user_id.to_s %>
          <div class="span3">
            <div class="btn-group" data-toggle="buttons-checkbox" style="text-align: center;">
              <%= link_to 'Edit', edit_idea_path(idea), :class => "btn btn-primary btn-mini" %> 
              <%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger btn-mini" %>
            </div>
          </div>
        <% end %>
      </div>

      <hr />
    
    </div>
  <% end %>

  <div class="flickr_pagination pagination-centered">
    <%= will_paginate @ideas, :class => "flickr_pagination"  %>
  </div>
</div>

app/views/ideas/new.html.erb
<legend><%= t :create_idea %></legend>

<%= render 'form' %>

app/views/ideas/show.html.erb
<div class="IdeaBlock row-fluid well well-large">

  <%  # 
  %>
  <div class="span9">
    <%= link_to 'Back', ideas_path, :class => "btn btn-primary btn-normal" %> <br /><br />

    <%= link_to 'I like this idea', scoreup_idea_path(@idea), :class => "btn btn-success btn-mini" %> 
    
    <% if @idea.status == 0 || @idea.status.nil? %> <s> <% end %>
    <strong><%= @idea.category.name %> - <%= @idea.title %> </strong>
    <% if @idea.status == 0 || @idea.status.nil? %> </s> <% end %>

    <div class="IdeaAuthor">
        (from @<%= @idea.user.nickname if @idea.user  %>, 
        <%= distance_of_time_in_words_to_now @idea.updated_at %>)
    </div> <br />
    <div class="IdeaBody">
        <%= simple_format(@idea.body) %>
    </div>
  </div>

  <div class="span3">
    <div class="btn-group" data-toggle="buttons-checkbox" style="text-align: center;">
      <% if @idea.user_id == session[:current_user_authenticated] %>
        <%= link_to 'Edit', edit_idea_path(@idea), :class => "btn btn-primary btn-mini" %> 
        <%= link_to 'Destroy', @idea, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger btn-mini" %>
      <% end %>
    </div>
    <div class="IdeaScore"><%= @idea.score %></div>
  </div>

  <%= render 'comments/list.html.erb' %>

</div>